name = "icon-canva-app"
compatibility_date = "2024-12-01"
node_compat = true

[env.production]
workers_dev = false

[build]
command = "npm run build"

# Node.js compatibility
compatibility_flags = ["nodejs_compat"]
